2014-08-27 03:39:42,497 manager INFO 1.1.0
2014-08-27 03:39:42,512 manager INFO Copyright (C) 2003-2010
2014-08-27 03:39:42,512 manager INFO   Noriaki Ando
2014-08-27 03:39:42,512 manager INFO   Intelligent Systems Research Institute, AIST
2014-08-27 03:39:42,512 manager INFO Manager starting.
2014-08-27 03:39:42,513 manager INFO Starting local logging.
2014-08-27 03:39:42,532 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2014-08-27 03:39:44,538 ManagerServant INFO Master manager not found
2014-08-27 03:39:44,539 manager ERROR Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\OpenRTM_aist\Manager.py", line 1751, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 2] No such file or directory: '/var/log/rtcmanager.ref'

2014-08-27 03:39:50,483 SdoServiceAdmin WARNING No available SDO service in the factory: 
2014-08-27 03:39:50,483 SdoServiceAdmin ERROR type  already exists.
2014-08-27 03:39:50,486 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2014-08-27 03:39:50,486 SdoServiceAdmin ERROR type ff3ed6da-d7fe-429e-b107-db83f2c9cf2f already exists.
2014-08-27 03:39:53,308 DataBase ERROR interface matched with old descriptor: port.DataBase::mDataBase.database
2014-08-27 03:43:19,749 DataBase ERROR interface matched with old descriptor: port.DataBase::mDataBase.database
2014-08-27 03:43:24,430 DataBase ERROR interface matched with old descriptor: port.DataBase::mDataBase.database
2014-08-27 04:15:05,078 DataBase ERROR interface matched with old descriptor: port.DataBase::mDataBase.database
2014-08-27 04:15:09,335 DataBase ERROR interface matched with old descriptor: port.DataBase::mDataBase.database
